default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { '1' } %>
  host: <%= ENV.fetch("PG_HOST") { '127.0.0.1' } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>

development:
  <<: *default
  database: internal_wallet

test:
  <<: *default
  database: internal_wallet_test

production:
  <<: *default
  database: your_production_database_name
  username: <%= ENV['PG_PROD_USERNAME'] %>
  password: <%= ENV['PG_PROD_PASSWORD'] %>
  host: <%= ENV['PG_PROD_HOST'] %>
  port: <%= ENV['PG_PROD_PORT'] { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>